environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '4'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - choco install chromium
  - npm install

test_script:
  - npm test

build: off
