language: node_js
node_js:
  - "4"
  - "5"

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update

  - sudo apt-get install google-chrome-stable
  - sudo apt-get install chromium-browser
  - sudo apt-get install firefox

  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

test:
  - node --version
  - npm --version
  - npm test
