language: c
os:
  - osx

env:
  - NODE_VERSION="4"
  - NODE_VERSION="5"

before_install:
  # Install runtime
  - brew install nvm
  - export NVM_DIR=~/.nvm
  - source $(brew --prefix nvm)/nvm.sh
  - nvm install $NODE_VERSION

  # Install browsers
  - brew tap caskroom/cask
  - brew cask install chromium electron firefox google-chrome

install:
  # Install dependencies
  - npm install

cache:
  directories:
    # Cache runtimes, compilation is taking up to 20 minutes
    - ~/.nvm
    # Cache modules
    - node_modules

script:
  - node --version
  - npm --version
  - npm test
