repository: caspervonb/node-browser_process
google_analytics: 'UA-48351156-6'

markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  toc_levels: "2,3"

gems:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-mentions

exclude:
  - makefile
